
import React from "react";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from "../../context/AuthContext";
import { ProfileProvider } from "../../context/ProfileContext";
import { ChatProvider } from "../../context/ChatContext";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProfileProvider>
        <ChatProvider>
        <AuthProvider>
        
        <div style={{"display":"flex","width":"100%"}}>
      <ToastContainer/>
        {children}
        </div>
        
        </AuthProvider>
        </ChatProvider>
        </ProfileProvider>
        </body>
    </html>
  )
}
